### ISSUE TITLE
User model present in model-config.json

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback-example-access-control#103] opened 2017-02-20 22:11 UTC
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Additional information (Node.js version, LoopBack version, etc)
Both the base  [`User` model](https://github.com/strongloop/loopback-example-access-control/blob/589f8851f31389f5e2186eeb91f161e743ee3f8c/server/model-config.json#L10-L13) and a custom [`user` model](https://github.com/strongloop/loopback-example-access-control/blob/589f8851f31389f5e2186eeb91f161e743ee3f8c/server/model-config.json#L30-L33) (which extends `User`) are present in the `model-config.json`. I don't believe this is intentional and the base `User` model should be removed from the config. 

At the minimum it is confusing for files such as [`common/models/user.js`](https://github.com/strongloop/loopback-example-access-control/blob/589f8851f31389f5e2186eeb91f161e743ee3f8c/common/models/user.js), it is not immediately clear which model this would apply to.

To resolve, the base `User` model should be removed or the custom `user` model should be renamed to something else such as `Account`.

**Comment by superkhau** [comment] 2017-02-20 22:47
@greaterweb It is intentional. `User` is a builtin model and `user` is a user-defined model. We really should just rename it `customer` something to prevent confusion. It's been there for a long time -- if you would like to contribute a fix, I can help you get it landed.

Note that `User` is private while `user` is public in the `model-config`.

**Closed by superkhau** 2017-02-20 22:47 UTC

**Comment by superkhau** [comment] 2017-02-20 22:48
cc @crandmck -- we really should get this fixed lol still going around

**Comment by greaterweb** [comment] 2017-02-20 23:05
Thank you for the prompt response. 

Could you please explain why you would need the builtin `User` model if you've created a custom model which extends it? I've got a fair amount of experience in using Loopback v2 and many times using the built in `User` model as the base for my custom user/account model. 

Is something different in v3 which has this as the recommended approach? I don't have any instances where the builtin model was required in addition to the model I created. It's not entirely clear in this repo why you would need both and I can't find anything in the docs supporting the need to do so.

I realize the issue system isn't intended to be a support mechanism but in this case this ticket is actually secondary to a bug I'm was about to submit to the main loopback repo.

**Comment by superkhau** [comment] 2017-02-21 00:52
@greaterweb The builtin `User` is used for various parts of the LB system -- ie. ACLs, Roles, AccessToken, etc. So it needs to be part of a default LB scaffold -- that said, it is restricting in many ways so we recommend extending it to enable full customization.

**Comment by greaterweb** [comment] 2017-02-21 01:07
@superkhau you may wish to follow the discussions in strongloop/loopback#3215

I guess what we are really looking at is the larger topic on whether or not it is required to include the `User` model reference in `model-config.json` if I'm extending it. Prior to v3.3.0 it wasn't required to do so to get the "out of the box" benefits of the `User` model, with the latest loopback release that appears to have changed.

**Comment by superkhau** [comment] 2017-02-21 01:14
Yes, I saw your comment with @raymondfeng (especially this one https://github.com/strongloop/loopback/issues/3215#issuecomment-281207659) which is correct. I wasn't sure if you could've removed `User` in versions <3.3.0 -- did you try reproducing on a fresh 2.x project vs 3.x to prove it? Otherwise, it's a breaking change that should've never landed since it wasn't mentioned in the 3.x docs IMO. Anyways, lets confirm first.

**Comment by crandmck** [comment] 2017-02-21 19:06
> we really should get this fixed lol still going around

The general concept of extending the User model for your own purposes is laid out pretty clearly in 
http://loopback.io/doc/en/lb3/Managing-users.html.  However, it doesn't say you have to leave the entry for User in `model-config.json`.  I always assumed that to extend a model, you would leave the base model "as is".   LMK if I should clarify.

Also, if something _did_ change wrt this between v2 & v3, then we definitely need to document it.  I certainly was not aware of it!

**Comment by superkhau** [comment] 2017-02-22 03:08
The bug is being handled by @miroslav at https://github.com/strongloop/loopback/issues/3215#issuecomment-281335305 already. No doc changes are required ATM.

What I meant was change the `user` to `Customer` or something to prevent confusion in the example instead of `User` to `user` remember? This hasn't changed for a long time now. ;)

**Comment by crandmck** [comment] 2017-02-22 19:56
> What I meant was change the user to Customer or something to prevent confusion in the example instead of User to user remember? This hasn't changed for a long time now. ;)

Oh, right... It would be a good change, and should be relatively straightforward.  Perhaps something for @siddhipai ?

**Comment by superkhau** [comment] 2017-02-22 22:17
@crandmck Good idea. :)

**Comment by superkhau** [comment] 2017-02-22 22:19
@siddhipai See https://github.com/strongloop/loopback-example-access-control/issues/73, reassigning this to you. Also try to go throught his example when you have time too.
