### ISSUE TITLE
ValidationError: The `team` instance is not valid. Details: `memberId` can't be blank (value: NaN)

### ISSUE THREAD

**Issue by LuigiFrattolillo** [strongloop/loopback-example-access-control#67] opened 2015-11-11 15:34 UTC
Hi, i'm trying to use Mongodb as data source, but i get this error during sample creations:

Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Created users: [ { username: 'John',
    email: 'john@doe.com',
    password: '$2a$10$eQQuWFROKW1SWFC1VjOBUOEWtq4Gu8aqqVXTa8RgWwB5AjCPGvRzO',
    id: 56435f381fded18a4f15af6d },
  { username: 'Jane',
    email: 'jane@doe.com',
    password: '$2a$10$r8Lffj2OPEp5W.clO0.HvOuXclbwOURRHDDOAdeyLR3BJhrWdpdNS',
    id: 56435f381fded18a4f15af6e },
  { username: 'Bob',
    email: 'bob@projects.com',
    password: '$2a$10$N/JyYFKX9/PO0cg9LjTmZOqmSTAJjy6UgEc6C13TmSpM.VxqNodqu',
    id: 56435f381fded18a4f15af6c } ]
Created project: { name: 'project1',
  balance: 100,
  ownerId: 56435f381fded18a4f15af6d,
  id: 56435f3a1fded18a4f15af6f }

/Users/melaporpora/working-sites/loopback-example-access-control/server/boot/sample-models.js:30
        if (err) throw err;
                 ^
ValidationError: The `team` instance is not valid. Details: `memberId` can't be blank (value: NaN).,ValidationError: The `team` instance is not valid. Details: `memberId` can't be blank (value: NaN).

**Comment by richardpringle** [comment] 2015-11-17 21:31
Hey @LuigiFrattolillo, for me to help you, I'll need you to do the following:
could you please provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

Hopefully I'll be able to help once your repo is up!

**Comment by jasiedu** [comment] 2016-01-15 23:05
You can reproduce this issue by using mongo as your database instead of the memory store. Thanks

**Comment by richardpringle** [comment] 2016-01-16 02:00
As it turns out, there are several major problems with this example. Work is being done on improving it and I will take a look and make sure that memory isn't the only datasource that can be used.

@jasiedu, if someone forks this repo and adds a script to populate the mongoDB database and change the datasource, etc. it makes the reproduction process much faster for me so I can escalate the issue as an official bug, which in turn means that it will get fixed sooner. It also allows me to spend more time fixing bugs instead of reproducing and everyone benefits. Make sense?

**Comment by chertpong** [comment] 2016-02-02 20:15
The issue caused by ownerId and memberId in models/team.json are both number
while id in Mongodb should be string

here is solution (It's my first time using fork to fix someone's issue, is this right?)
https://github.com/chertpong/loopback-example-access-control/commit/5d76698e67ec33405e562bdf45521e927e3ca829

**Comment by tonyffrench** [comment] 2016-02-16 01:50
LGTM @chertpong you solution is good, you actually only need to change memberId, because ownerId is referenced as a foreign key and inherits that type. Changing both is the safe answer here.

**Comment by richardpringle** [comment] 2016-02-16 02:00
Sorry @chertpong, your comment slipped through my long list of GitHub notifications!
Thanks for the response @tonyffrench

**Comment by richardpringle** [comment] 2016-02-16 02:03
@chertpong, could you make a pull request? I know it's a small change but you should get credit for the fix! If not, I will make the change.

Thank you

**Comment by chertpong** [comment] 2016-02-18 14:43
@richardpringle Thank you! and could you check my pull request? It's my first time doing this. 
https://github.com/strongloop/loopback-example-access-control/pull/71

**Comment by richardpringle** [comment] 2016-03-14 11:50
Fixed as per https://github.com/strongloop/loopback-example-access-control/pull/71. Closing

**Closed by richardpringle** 2016-03-14 11:50 UTC
Labels: bug, waiting
