### ISSUE TITLE
/users/:id/account not accessible

### ISSUE THREAD

**Issue by nicnocquee** [strongloop/loopback-example-access-control#8] opened 2014-03-19 00:49 UTC
Hi, 

I'm trying to wrap my head around loopback's ACL but I couldn't figure out why `/users/:id/account ` is not accessible even when logged in user calls it. Keeps getting access denied.

`/accounts/:id?access_token=<token>` also got access denied. 

I thought since `user` belongs to `account` and `account` has acl:

```

{
          "accessType": "*",
          "permission": "ALLOW",
          "principalType": "ROLE",
          "principalId": "$owner"
}

```

account can be accessed by the owner which is the user it is associated with.

Enlighten me, please :smile:

**Comment by ryncorbeil-ssf** [comment] 2015-09-17 22:45
What is the status of this issue please?  It appears that the original behavior stated above ("It seems that we pick the ‘DENY’ rule from the following acls") is still in force.  Thanks.

**Comment by ryncorbeil-ssf** [comment] 2015-09-18 00:35
If the issue has in fact been addressed, does any sample project exist?

What I would expect, would be that a user logged in would be able to 'find' only those model instances (records) that she created, and not any others.  However the user 'finds' ALL records, even though she did not create. Am I not understanding the semantics of the $owner role?

Googleing, I found that it is necessary to create a 'belongsTo' relation, and explicitly create a property which serves as the foreignKey.  When an instance is created, is the id of the 'owner' inserted as the foreign key automatically, or must the creator set that explicitly? I've tried the latter, with the following results...  (Thanks in advance)

{
  "name": "casinoUser",
  "base": "User",
  "strict": false,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "firstName": {
      "type": "string",
      "required": true
    },
    "lastName": {
      "type": "string",
      "required": true
    },
    "casinoId": {
      "type": "string",
      "required": true
    },
    "ownerId": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "casino": {
      "type": "belongsTo",
      "model": "casino",
      "foreignKey": "casinoId"
    },
    "user": {
     "type": "belongsTo",
     "model": "User",
     "roles": ["owner"],
     "foreignKey": "ownerId"
   }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}

loopback:security:role isInRole(): $everyone +24s
  loopback:security:access-context ---AccessContext--- +1ms
  loopback:security:access-context principals: +1ms
  loopback:security:access-context principal: {"type":"USER","id":"55fa0f3e2fe396f3155d9a0e"} +1ms
  loopback:security:access-context modelName casinoUser +1ms
  loopback:security:access-context modelId undefined +1ms
  loopback:security:access-context property find +2ms
  loopback:security:access-context method find +1ms
  loopback:security:access-context accessType READ +4ms
  loopback:security:access-context accessToken: +1ms
  loopback:security:access-context   id "LaghUTG5gOBYr4eOD7B6zxJxnIGElg3wzjmZLT2coFlrIg5UdMnmxppUwGT8i415" +0ms
  loopback:security:access-context   ttl 1209600 +1ms
  loopback:security:access-context getUserId() 55fa0f3e2fe396f3155d9a0e +1ms
  loopback:security:access-context isAuthenticated() true +1ms
  loopback:security:role Custom resolver found for role $everyone +1ms
  loopback:security:role isInRole(): $everyone +1ms
  loopback:security:access-context ---AccessContext--- +1ms
  loopback:security:access-context principals: +1ms
  loopback:security:access-context principal: {"type":"USER","id":"55fa0f3e2fe396f3155d9a0e"} +0ms
  loopback:security:access-context modelName casinoUser +1ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property find +1ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +1ms
  loopback:security:access-context   id "LaghUTG5gOBYr4eOD7B6zxJxnIGElg3wzjmZLT2coFlrIg5UdMnmxppUwGT8i415" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() 55fa0f3e2fe396f3155d9a0e +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role Custom resolver found for role $everyone +1ms
  loopback:security:role isInRole(): admin +0ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: +1ms
  loopback:security:access-context principal: {"type":"USER","id":"55fa0f3e2fe396f3155d9a0e"} +0ms
  loopback:security:access-context modelName casinoUser +0ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property find +0ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "LaghUTG5gOBYr4eOD7B6zxJxnIGElg3wzjmZLT2coFlrIg5UdMnmxppUwGT8i415" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() 55fa0f3e2fe396f3155d9a0e +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role Custom resolver found for role admin +0ms
  loopback:security:role isInRole(): $owner +0ms
  loopback:security:access-context ---AccessContext--- +1ms
  loopback:security:access-context principals: +0ms
  loopback:security:access-context principal: {"type":"USER","id":"55fa0f3e2fe396f3155d9a0e"} +0ms
  loopback:security:access-context modelName casinoUser +0ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property find +0ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "LaghUTG5gOBYr4eOD7B6zxJxnIGElg3wzjmZLT2coFlrIg5UdMnmxppUwGT8i415" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() 55fa0f3e2fe396f3155d9a0e +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role Custom resolver found for role $owner +0ms
  loopback:security:acl The following ACLs were searched:  +1ms
  loopback:security:acl ---ACL--- +1ms
  loopback:security:acl model casinoUser +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId admin +0ms
  loopback:security:acl accessType * +0ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7508
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model casinoUser +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +1ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType * +0ms
  loopback:security:acl permission DENY +0ms
  loopback:security:acl with score: +0ms 7495
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model casinoUser +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType * +0ms
  loopback:security:acl permission DENY +0ms
  loopback:security:acl with score: +0ms 7495
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:access-context ---AccessRequest--- +0ms
  loopback:security:access-context  model casinoUser +1ms
  loopback:security:access-context  property find +0ms
  loopback:security:access-context  accessType READ +0ms
  loopback:security:access-context  permission ALLOW +0ms
  loopback:security:access-context  isWildcard() false +0ms
  loopback:security:access-context  isAllowed() true +0ms

**Comment by vabnirvana** [comment] 2015-11-12 12:02
This does not solve the problem. After updating this and also grating all the things to acl for user model thats extend from User Model, I still get 401 : AUTHORIZATION_REQUIRED", "stack": "Error: Authorization in normal /get calls for user.

**Comment by bekerov** [comment] 2015-11-16 05:02
same problem.

**Comment by superkhau** [comment] 2015-11-16 21:05
@richardpringle Can you try to reproduce this issue and see if it's still relevant?

**Comment by richardpringle** [comment] 2015-11-16 22:33
@superkhau, it's still relevant, I put a bug label on the issue

**Comment by superkhau** [comment] 2015-11-16 23:27
Cool, I'll assume you got it then.

**Comment by richardpringle** [comment] 2015-11-30 20:22
@nicnocquee , @ryncorbeil-ssf , and @vabnirvana, I took a deeper look into this issue and it turns out that the functionality of the example is exactly as expected.
The acl,
```
 {
   "accessType": "*",
   "principalType": "ROLE",
   "principalId": "$everyone",
   "permission": "DENY"
 }
```
puts a blanket deny on every api endpoint. Each other acl gives specific ROLE access to the following endpoints:
```
projects/listProjects
projects/
projects/{id}
projects/donate
projects/withdraw
```
with the respective properties:
```
listProjects
find
findById
donate
withdraw
```
Any other endpoints will not work, for example `projects/{id}/user`.

So, I am going to close the issue. If you have any additional questions or comments please post them [here](https://groups.google.com/forum/#!forum/loopbackjs). See https://github.com/strongloop/loopback/wiki/Questions for more details on posting questions.

**Comment by richardpringle** [comment] 2015-11-30 20:33
@ryncorbeil-ssf, I am not quite clear on what your question is.
 I believe that the foreign automatically inserted if it is not explicitly declared ([see docs](https://docs.strongloop.com/display/public/LB/BelongsTo+relations)).  

As for your specific case, it is not quite clear what you are trying to accomplish. I think the best place for you to get your question answered is at https://groups.google.com/forum/#!forum/loopbackjs. 

please read the [questions wiki](https://github.com/strongloop/loopback/wiki/Questions) for more info to find the best way to get your questions answered.

Also, instead of posting code along with the console output, it's easier for someone to reproduce your issue with an actual repo, [checkout the bug-report section of the wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

Good luck!

**Closed** 2015-11-30 20:46 UTC
Labels: #wip, Beginner Friendly, bug, Slipped, triage
